### PR TITLE
Initial Contract & Testing Setup

### PR DESCRIPTION
**Pull request by apbendi**
As a starting point for the contract setup, I imported the Moloch sources with OZ imports (as we did previously) and set up testing based on the OpenZepplin helpers from a forked ganache. Let me know what you think!

### CODE REVIEW

**Comment by apbendi** [comment]
Oh boy, here we go again! Yes, works for me. What version of ganache-cli are you using? You have an Infura id defined in your .env?

**Comment by mds1** [comment]
Yep, `INFURA_ID` is defined, using Ganache CLI v6.9.1 (ganache-core: 2.10.2)

**Comment by abcoathup** [comment]
Test passes with timeout disabled or increased. 

See details in the forum:
https://forum.openzeppelin.com/t/tests-are-failing-using-ganache-fork-with-openzeppelin-test-environment-with-a-timeout-error/2704/4?u=abcoathup

**Comment by mds1** [comment]
@apbendi Ok got everything working now. Made some changes to the package.json scripts to help prevent some of the issues I was having

@abcoathup Thanks again for your help!

**Comment by apbendi** [comment]
Thanks @abcoathup, huge help! I wonder what the bottleneck is and why it's so different across systems. Mine takes ~4s on a 4 year old macbook pro, though I do have fast broadband. Wonder if that's the issue as it relates to forking and pulling state from the network. Anyway appreciate it! 🍻

**Comment by ylv-io** [comment]
@mds1 out of curiosity what it was?

**Comment by mds1** [comment]
@ylv-io I'm not sure what the root cause was, but the only changes between the initial failing version and the working version are that I (1) deleted the contract build directory and re-compiled, and (2) deleted the node_modules directory and reinstalled packages. But now the tests pass after taking ~6s to start up

**Pull request merged**
